add: adding new cicd for frontend

diff --git a/.github/workflows/policy_validation.yaml b/.github/workflows/policy_validation.yaml
--- a/.github/workflows/policy_validation.yaml
+++ b/.github/workflows/policy_validation.yaml
@@ -11,7 +11,10 @@ jobs:
 
     steps:
       - name: Checkout repo
-        uses: actions/checkout@v3
+        uses: actions/checkout@v4
+
+      - name: Install Helm
+        uses: azure/setup-helm@v3
 
       - name: Install Kyverno CLI
         run: |
@@ -21,47 +24,42 @@ jobs:
           sudo mv kyverno /usr/local/bin/
           kyverno version
 
-      - name: Validate Kubernetes manifests against policies
+      - name: Render Helm templates
         run: |
-          echo "🔍 Running Kyverno policy validation..."
-          echo "----------------------------------------"
+          helm template superheros \
+            gc-industries-devops-superheros/helm/superheros \
+            > rendered.yaml
 
-          # Run silently and store output
-          kyverno apply kyverno_policy \
-            --resource manifests/deployment.yaml \
-            --resource manifests/namespace.yaml \
+      - name: Run Kyverno validation
+        run: |
+          echo "🔍 Running Kyverno validation..."
+
+          kyverno apply \
+            gc-industries-devops-superheros/infra/kyverno_policy \
+            --resource rendered.yaml \
             --policy-report > kyverno-report.txt || true
 
           echo ""
           echo "📊 ===== SUMMARY ====="
-          echo ""
 
-          echo "Result Counts:"
           grep "result:" kyverno-report.txt | sort | uniq -c || true
 
           echo ""
-          echo "❌ FAILED RULES:"
-          grep -B 2 -A 3 "result: fail" kyverno-report.txt || echo "No failures 🎉"
+          echo "❌ FAILED:"
+          grep -B 2 -A 3 "result: fail" kyverno-report.txt || echo "None 🎉"
 
-          echo ""
-          echo "✅ PASSED RULES:"
-          grep -B 2 -A 2 "result: pass" kyverno-report.txt || echo "No passes found"
-
-          echo ""
-          echo "----------------------------------------"
-
-      - name: Fail if policy violations found
+      - name: Fail if violations found
         run: |
           if grep -q "result: fail" kyverno-report.txt; then
-            echo "❌ Policy violations detected. Failing pipeline."
+            echo "❌ Policy violations found"
             exit 1
           else
-            echo "✅ All policies passed successfully."
+            echo "✅ All good"
           fi
 
-      - name: Upload Kyverno Report (Artifact)
+      - name: Upload Report
         if: always()
         uses: actions/upload-artifact@v4
         with:
-          name: kyverno-policy-report
+          name: kyverno-report
           path: kyverno-report.txt
